"""Add message_count and is_archived to ChatSession

Revision ID: add_session_fields
Revises: 
Create Date: 2025-01-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_session_fields'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('chat_sessions', sa.Column('reasoning_content', sa.Text(), nullable=True))
    
    # Set default values
    op.execute("UPDATE chat_sessions SET message_count = 0 WHERE message_count IS NULL")
    op.execute("UPDATE chat_sessions SET is_archived = false WHERE is_archived IS NULL")
    
    # Make columns non-nullable
    op.alter_column('chat_sessions', 'message_count', nullable=False)
    op.alter_column('chat_sessions', 'is_archived', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'reasoning_content')
    op.drop_column('chat_sessions', 'is_archived')
    op.drop_column('chat_sessions', 'message_count')
    # ### end Alembic commands ###